{% set version = "1.0.4" %}
{% set build = 0 %}

package:
  name: theano
  version: {{ version }}

source:
  fn: Theano-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/T/Theano/Theano-{{ version }}.tar.gz
  sha256: 35c9bbef56b61ffa299265a42a4e8f8cb5a07b2997dabaef0f8830b397086913
  patches:
    - 0001-Add-support-for-custom-compiler.patch
    - 0002-Extend-default-flags-for-win-32.patch

build:
  number: {{ build }}
  script:
    - '[[ -f theano/scan_module/c_code/scan_perform.c ]] && rm -f theano/scan_module/c_code/scan_perform.c'  # [unix]
    - if exist theano\scan_module\c_code\scan_perform.c del /q theano\scan_module\c_code\scan_perform.c      # [win]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools
    - cython
  run:
    - {{ compiler('cxx') }}  # [unix]
    - python
    - libpython >=2.0        # [win]
    - m2w64-toolchain        # [win]
    - setuptools
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14
    - {{ pin_compatible('pygpu', '0.7', max_pin='0.8') }}   # [not osx]

test:
  requires:
    - nose >=1.3.0
    - nose-parameterized >=0.5.0
    - parameterized

  imports:
    - theano
    - theano.compile
    - theano.compile.sandbox
    - theano.compile.tests
    - theano.gof
    - theano.gof.tests
    - theano.gpuarray
    - theano.gpuarray.dnn
    - theano.gpuarray.linalg
    - theano.misc
    - theano.sandbox
    - theano.scalar
    - theano.scalar.tests
    - theano.sparse
    - theano.sparse.tests
    - theano.tensor
    - theano.tensor.nnet
    - theano.tensor.nnet.tests
    - theano.tensor.signal
    - theano.tensor.signal.tests
    - theano.tensor.tests
    - theano.tests

  source_files:
    - theano/tests

  commands:
    - MKL_THREADING_LAYER=GNU theano-cache help            # [unix]
    - MKL_THREADING_LAYER=GNU theano-nose -v theano/tests  # [unix]
    - set MKL_THREADING_LAYER=GNU&& theano-cache help            # [win]
    - set MKL_THREADING_LAYER=GNU&& theano-nose -v theano/tests  # [win]

about:
  home: http://deeplearning.net/software/theano/
  license: BSD 3-Clause
  summary: 'Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.'
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abergeron
    - jakirkham
    - ocefpaf
    - ericmjl
