{% set version = "1.0.0" %}
{% set build = 0 %}

package:
  name: theano
  version: {{ version }}

source:
  fn: Theano-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/T/Theano/Theano-{{ version }}.tar.gz
  sha256: 7bc82e4fcaac023cac23c390b30d5df81bc09d33568812df75b0bd2b86d2fa8f

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - six >=1.9.0
    - numpy >=1.9.1
    - scipy >=0.14
    - pygpu >=0.6.5,<0.7

test:
  requires:
    - nose >=1.3.0
    - nose_parameterized >=0.5.0
  imports:
    - theano
    - theano.compile
    - theano.compile.sandbox
    - theano.compile.tests
    - theano.gof
    - theano.gof.tests
    - theano.misc
    - theano.sandbox
    - theano.sandbox.cuda
    - theano.sandbox.cuda.tests
    - theano.scalar
    - theano.scalar.tests
    - theano.sparse
    - theano.sparse.tests
    - theano.tensor
    - theano.tensor.nnet
    - theano.tensor.nnet.tests
    - theano.tensor.signal
    - theano.tensor.signal.tests
    - theano.tensor.tests
    - theano.tests

about:
  home: http://deeplearning.net/software/theano/
  license: BSD 3-Clause
  summary: 'Optimizing compiler for evaluating mathematical expressions on CPUs and GPUs.'
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abergeron
    - jakirkham
    - ocefpaf
    - ericmjl
