travis:
  secure:
    BINSTAR_TOKEN: p0LVulWmexnSEjWAGMnmtpPGz/tVYj5q5uf6oyRaB3nVgdca+B7rWGbHprBJ/oawHo6hsthz7xA2PcaCNNLbyHE4kiRDN9AdtUyQV0x6LTKFIPhKYSgeX3BldfBgJeQJ6VqPYg0C9MNQrNvLecwzCPbeCs4IqImlwqYHKc5z0xu2qF75CtkjbU3EG6agHqgnP4Wugh0JzGZRdL384ZD1Om8rlb4uxbF8WxWtMCtGwujsTDF2957cMu09700HmTH6UJZEJpX/J2QKXxiolwZbwxHFue02Vpj6Sy+PP3I6O684Ps+Ur8Uei0UyxftzoweSLCJqKu4AQL4j02mqhTZe4QZOlX0JyhucyVv1cBnlc9610oqaqDKKSypBeQYQxRNGsRpEboZ87IjAl/ETzApDR+4uXZQ9tKVD8BEBcnXlDLTtz7nu14iN4PUJVLOsW47aeapERe21IowzeDiDfJOjw8bEPkpKUm5zYMy7xuWe5+AUEmy8sSzy3Hk6FNdwnVKaCvTDcpcxHXtcRe5L7ZBbdl7g3Sju7Z/G8nnx9bY3kWHMBhJ6lXm7VexvLgNIfez6L6NRUqQ51QgxhHzYLlRK85F0kH9vGoTv3Ej6h9/eEGo/+7+Fm0EBl59F2S1dv3C7/eAhAGl2IkwbZVThSLy6hbNAGYSxzUyBEfGPuGMtH50=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
