travis:
  secure:
    BINSTAR_TOKEN: NalBkS7VqNxaXZ1OUKPOgiQl+Jepb40ku0+UBeJQAdK5qzB/Zgs38Os8P2capVqJuZQnu8SwrDA01udKcw/JEPX3JwM1wFanp9ku8qt8IXqC7VKPUED1BrvnB+NWjN16WePSrJC2Xy0bG+1h2Ug6M/sB5HMlhMHQSTdeoq3Bgj+buEk1e5RklPXOtW1RzXPJofpTVQNTHNmBhEpaCFfq2anB0Jyzk78ChiqMBT+SWTQocGvpgz9Gl/qtAfDvdFEaTFzEaByacAGaDI7XhCN9XPNZgIwa0G35wqLmb8riJjLjlWDBIz0QqRIA7rPKlU9aoiBDT5l/5+Y/qmOPqHw0kExYDVVUj9fSHVnq3x+NxZAroVXCY5auMHes3GfRMi3woOMyvEtqddFtcl7OxMyRvzs0CLBCjaFwN+hOb6f+9SRALXYz4TaPUdDy4sObxL/P+E+Qrvx9R3ck553ukd0JLH52yUx7K6WDrtoEHq5kbXiqsVBKk1A0CN6aLAbEqjh7cSvm0yBpJ8wVaw3q4CM+1fPcKke+cpPeKmh9iqTrOJeG5173e8Qk49klo+EH504pQzrzWwT1ylIjtolexPzv5qmewYotyJWsnJP4sgBA2srUMNqqjoPDn1hH1vjjs+5LFRv1nOHOSiwgvlBhsIQQl3BUe626McVpKf2N/K1N92o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
